module ComoniconGUI
import Base
using Poptart.Desktop
using ExprTools
# import Comonicon.codegen
using Comonicon
using Comonicon.CodeGen: nrequired_args, hasparameters, read_forward, read_arg, read_flag, pushmaybe!
using Comonicon.CodeGen: read_flag, regex_flag, read_arg, regex_flag, regex_option, read_match, regex_short_flag
using Comonicon.CodeGen: regex_short_option, xmatch, xerror, xparse, xparse_args, xparse_varargs, xprint_help, xprint_version
using Comonicon.Types
import Comonicon
import Comonicon.Parse
using Comonicon.Parse: CACHE_FLAG, create_cache, cachefile, cachedir

include("codegen/poptart.jl")

"""
    write([io], cmd::EntryCommand)

Write the generated CLI script into a Julia script file. Default is the [`cachefile`](@ref).
"""
function Base.write(io::IO, x::EntryCommand)
    println(io, "#= generated by Comonicon =#")
    main_code = prettify(codegen(x))
    if main_code.head == :block
        for arg in main_code.args
            println(io, arg)
        end
    else
        println(io, main_code)
    end
    println(io, "command_main()")
end

end
